export const CookieConstants = {
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  IS_LOGGED_IN: 'IS_LOGGED_IN',
  LANGUAGE: 'LANG',
  THEME: 'THEME',
  EMAIL: 'EMAIL',
  ROLE: 'ROLE',
  IS_FIRST_LOGIN: 'IS_FIRST_LOGIN',
};

export const LocalStorageConstants = {
  USER_ID: 'USER_ID',
  FIRST_NAME: 'FIRST_NAME',
  LAST_NAME: 'LAST_NAME',
  FULL_NAME: 'FULL_NAME',
  AVATAR: 'AVATAR',
  COVER_BACKGROUND: 'COVER_BACKGROUND',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  REDUX_STATE: 'REDUX_STATE',
};
