INSERT IGNORE INTO countries (name, en_name, is_disable) VALUES
                                       ('Đan Mạch','Denmark',false),
('Anh','England',false),
('Estonia','Estonia',false),
('Phần Lan','Finland',false),
('Iceland','Iceland',false),
('Ireland','Ireland',false),
('Latvia','Latvia',false),
('Lithuania','Lithuania',false),
('Bắc Ireland','Northern Ireland',false),
('Na Uy','Norway',false),
('Scotland','Scotland',false),
('Thụy Điển','Sweden',false),
('Vương Quốc Anh và Bắc Ireland','United Kingdom',false),
('Wales','Wales',false),
('Áo','Austria',false),
('Bỉ','Belgium',false),
('Pháp','France',false),
('Đức','Germany',false),
('Hà Lan','Netherlands',false),
('Thụy Sĩ','Switzerland',false),
('Albania','Albania',false),
('Croatia','Croatia',false),
('Cyprus','Cyprus',false),
('Hy Lạp','Greece',false),
('Ý','Italy',false),
('Bồ Đào Nha','Portugal',false),
('Serbia','Serbia',false),
('Slovenia','Slovenia',false),
('Tây Ban Nha','Spain',false),
('Belarus','Belarus',false),
('Bulgaria','Bulgaria',false),
('Cộng hòa Séc','Czech Republic',false),
('Hungary','Hungary',false),
('Ba Lan','Poland',false),
('Romania','Romania',false),
('Nga','Russia',false),
('Slovakia','Slovakia',false),
('Ukraine','Ukraine',false),
('Canada','Canada',false),
('Mexico','Mexico',false),
('Mỹ','United States',false),
('Cuba','Cuba',false),
('Guatemala','Guatemala',false),
('Jamaica','Jamaica',false),
('Argentina','Argentina',false),
('Bolivia','Bolivia',false),
('Brazil','Brazil',false),
('Chile','Chile',false),
('Colombia','Colombia',false),
('Ecuador','Ecuador',false),
('Paraguay','Paraguay',false),
('Peru','Peru',false),
('Uruguay','Uruguay',false),
('Venezuela','Venezuela',false),
('Georgia','Georgia',false),
('Iran','Iran',false),
('Iraq','Iraq',false),
('Israel','Israel',false),
('Jordan','Jordan',false),
('Kuwait','Kuwait',false),
('Lebanon','Lebanon',false),
('Lãnh thổ Palestin','Palestinian Territories',false),
('Ả-rập Saudi','Saudi Arabia',false),
('Syria','Syria',false),
('Thổ Nhĩ Kỳ','Turkey',false),
('Yemen','Yemen',false),
('Afghanistan','Afghanistan',false),
('Bangladesh','Bangladesh',false),
('Ấn Độ','India',false),
('Kazakhstan','Kazakhstan',false),
('Nepal','Nepal',false),
('Pakistan','Pakistan',false),
('Sri Lanka','Sri Lanka',false),
('Trung Quốc','China',false),
('Nhật','Japan',false),
('Mông Cổ','Mongolia',false),
('Triều Tiên','North Korea',false),
('Hàn Quốc','South Korea',false),
('Đài Loan','Taiwan',false),
('Cam-pu-chia','Cambodia',false),
('Indonesia','Indonesia',false),
('Lào','Laos',false),
('Malaysia','Malaysia',false),
('Myanmar','Myanmar',false),
('Philippines','Philippines',false),
('Singapore','Singapore',false),
('Thái Lan','Thailand',false),
('Việt Nam','Vietnam',false),
('Australia','Australia',false),
('Fiji','Fiji',false),
('New Zealand','New Zealand',false),
('Ethiopia','Ethiopia',false),
('Kenya','Kenya',false),
('Somalia','Somalia',false),
('Sudan','Sudan',false),
('Tanzania','Tanzania',false),
('Uganda','Uganda',false),
('Angola','Angola',false),
('Botswana','Botswana',false),
('Cộng hòa Dân chủ Congo','Democratic Republic of the Congo',false),
('Madagascar','Madagascar',false),
('Mozambique','Mozambique',false),
('Namibia','Namibia',false),
('Nam Phi','South Africa',false),
('Zambia','Zambia',false),
('Zimbabwe','Zimbabwe',false);


INSERT IGNORE INTO provinces (name, country_id, is_disable) VALUES
                             ( 'An Giang',88,false),
( 'Bà Rịa-Vũng Tàu',88,false),
( 'Bắc Giang',88,false),
( 'Bắc Kạn',88,false),
( 'Bạc Liêu',88,false),
( 'Bắc Ninh',88,false),
( 'Bến Tre',88,false),
( 'Bình Dương',88,false),
( 'Bình Định',88,false),
( 'Bình Phước',88,false),
( 'Bình Thuận',88,false),
( 'Cà Mau',88,false),
( 'Cần Thơ',88,false),
( 'Cao Bằng',88,false),
( 'Đà Nẵng',88,false),
( 'Đắk Lắk',88,false),
( 'Đắk Nông',88,false),
( 'Điện Biên',88,false),
( 'Đồng Nai',88,false),
( 'Đồng Tháp',88,false),
( 'Gia Lai',88,false),
( 'Hà Giang',88,false),
( 'Hà Nam',88,false),
( 'Hà Nội',88,false),
( 'Hà Tĩnh',88,false),
( 'Hải Dương',88,false),
( 'Hải Phòng',88,false),
( 'Hậu Giang',88,false),
( 'Hồ Chí Minh',88,false),
( 'Hòa Bình',88,false),
( 'Hưng Yên',88,false),
( 'Khánh Hòa',88,false),
( 'Kiên Giang',88,false),
( 'Kon Tum',88,false),
( 'Lai Châu',88,false),
( 'Lâm Đồng',88,false),
( 'Lạng Sơn',88,false),
( 'Lào Cai',88,false),
( 'Long An',88,false),
( 'Nam Định',88,false),
( 'Nghệ An',88,false),
( 'Ninh Bình',88,false),
( 'Ninh Thuận',88,false),
( 'Phú Thọ',88,false),
( 'Phú Yên',88,false),
( 'Quảng Bình',88,false),
( 'Quảng Nam',88,false),
( 'Quảng Ngãi',88,false),
( 'Quảng Ninh',88,false),
( 'Quảng Trị',88,false),
( 'Sóc Trăng',88,false),
( 'Sơn La',88,false),
( 'Tây Ninh',88,false),
( 'Thái Bình',88,false),
( 'Thái Nguyên',88,false),
( 'Thanh Hóa',88,false),
( 'Thừa Thiên-Huế',88,false),
( 'Tiền Giang',88,false),
( 'Trà Vinh',88,false),
( 'Tuyên Quang',88,false),
( 'Vĩnh Long',88,false),
( 'Vĩnh Phúc',88,false),
( 'Yên Bái',88,false);
