INSERT INTO countries (name) VALUES
                                 ('Việt Nam');
INSERT INTO provinces (name,country_id) VALUES
                             ( 'An Giang','1'),
                             ( 'Bà Rịa-Vũng Tàu','1'),
                             ( 'Bắc Giang','1'),
                             ( 'Bắc Kạn','1'),
                             ( 'Bạc Liêu','1'),
                             ( 'Bắc Ninh','1'),
                             ( 'Bến Tre','1'),
                             ( 'Bình Dương','1'),
                             ( 'Bình Định','1'),
                             ( 'Bình Phước','1'),
                             ( 'Bình Thuận','1'),
                             ( 'Cà Mau','1'),
                             ( 'Cần Thơ','1'),
                             ( 'Cao Bằng','1'),
                             ( 'Đà Nẵng','1'),
                             ( 'Đắk Lắk','1'),
                             ( 'Đắk Nông','1'),
                             ( 'Điện Biên','1'),
                             ( 'Đồng Nai','1'),
                             ( 'Đồng Tháp','1'),
                             ( 'Gia Lai','1'),
                             ( 'Hà Giang','1'),
                             ( 'Hà Nam','1'),
                             ( 'Hà Nội','1'),
                             ( 'Hà Tĩnh','1'),
                             ( 'Hải Dương','1'),
                             ( 'Hải Phòng','1'),
                             ( 'Hậu Giang','1'),
                             ( 'Hồ Chí Minh','1'),
                             ( 'Hòa Bình','1'),
                             ( 'Hưng Yên','1'),
                             ( 'Khánh Hòa','1'),
                             ( 'Kiên Giang','1'),
                             ( 'Kon Tum','1'),
                             ( 'Lai Châu','1'),
                             ( 'Lâm Đồng','1'),
                             ( 'Lạng Sơn','1'),
                             ( 'Lào Cai','1'),
                             ( 'Long An','1'),
                             ( 'Nam Định','1'),
                             ( 'Nghệ An','1'),
                             ( 'Ninh Bình','1'),
                             ( 'Ninh Thuận','1'),
                             ( 'Phú Thọ','1'),
                             ( 'Phú Yên','1'),
                             ( 'Quảng Bình','1'),
                             ( 'Quảng Nam','1'),
                             ( 'Quảng Ngãi','1'),
                             ( 'Quảng Ninh','1'),
                             ( 'Quảng Trị','1'),
                             ( 'Sóc Trăng','1'),
                             ( 'Sơn La','1'),
                             ( 'Tây Ninh','1'),
                             ( 'Thái Bình','1'),
                             ( 'Thái Nguyên','1'),
                             ( 'Thanh Hóa','1'),
                             ( 'Thừa Thiên-Huế','1'),
                             ( 'Tiền Giang','1'),
                             ( 'Trà Vinh','1'),
                             ( 'Tuyên Quang','1'),
                             ( 'Vĩnh Long','1'),
                             ( 'Vĩnh Phúc','1'),
                             ( 'Yên Bái','1');

