INSERT IGNORE INTO countries (name, en_name, is_disable, type, parent_id) VALUES
('Đan Mạch','Denmark',false'country',null),
('Anh','England',false'country',null),
('Estonia','Estonia',false'country',null),
('Phần Lan','Finland',false'country',null),
('Iceland','Iceland',false'country',null),
('Ireland','Ireland',false'country',null),
('Latvia','Latvia',false'country',null),
('Lithuania','Lithuania',false'country',null),
('Bắc Ireland','Northern Ireland',false'country',null),
('Na Uy','Norway',false'country',null),
('Scotland','Scotland',false'country',null),
('Thụy Điển','Sweden',false'country',null),
('Vương Quốc Anh và Bắc Ireland','United Kingdom',false'country',null),
('Wales','Wales',false'country',null),
('Áo','Austria',false'country',null),
('Bỉ','Belgium',false'country',null),
('Pháp','France',false'country',null),
('Đức','Germany',false'country',null),
('Hà Lan','Netherlands',false'country',null),
('Thụy Sĩ','Switzerland',false'country',null),
('Albania','Albania',false'country',null),
('Croatia','Croatia',false'country',null),
('Cyprus','Cyprus',false'country',null),
('Hy Lạp','Greece',false'country',null),
('Ý','Italy',false'country',null),
('Bồ Đào Nha','Portugal',false'country',null),
('Serbia','Serbia',false'country',null),
('Slovenia','Slovenia',false'country',null),
('Tây Ban Nha','Spain',false'country',null),
('Belarus','Belarus',false'country',null),
('Bulgaria','Bulgaria',false'country',null),
('Cộng hòa Séc','Czech Republic',false'country',null),
('Hungary','Hungary',false'country',null),
('Ba Lan','Poland',false'country',null),
('Romania','Romania',false'country',null),
('Nga','Russia',false'country',null),
('Slovakia','Slovakia',false'country',null),
('Ukraine','Ukraine',false'country',null),
('Canada','Canada',false'country',null),
('Mexico','Mexico',false'country',null),
('Mỹ','United States',false'country',null),
('Cuba','Cuba',false'country',null),
('Guatemala','Guatemala',false'country',null),
('Jamaica','Jamaica',false'country',null),
('Argentina','Argentina',false'country',null),
('Bolivia','Bolivia',false'country',null),
('Brazil','Brazil',false'country',null),
('Chile','Chile',false'country',null),
('Colombia','Colombia',false'country',null),
('Ecuador','Ecuador',false'country',null),
('Paraguay','Paraguay',false'country',null),
('Peru','Peru',false'country',null),
('Uruguay','Uruguay',false'country',null),
('Venezuela','Venezuela',false'country',null),
('Georgia','Georgia',false'country',null),
('Iran','Iran',false'country',null),
('Iraq','Iraq',false'country',null),
('Israel','Israel',false'country',null),
('Jordan','Jordan',false'country',null),
('Kuwait','Kuwait',false'country',null),
('Lebanon','Lebanon',false'country',null),
('Lãnh thổ Palestin','Palestinian Territories',false'country',null),
('Ả-rập Saudi','Saudi Arabia',false'country',null),
('Syria','Syria',false'country',null),
('Thổ Nhĩ Kỳ','Turkey',false'country',null),
('Yemen','Yemen',false'country',null),
('Afghanistan','Afghanistan',false'country',null),
('Bangladesh','Bangladesh',false'country',null),
('Ấn Độ','India',false'country',null),
('Kazakhstan','Kazakhstan',false'country',null),
('Nepal','Nepal',false'country',null),
('Pakistan','Pakistan',false'country',null),
('Sri Lanka','Sri Lanka',false'country',null),
('Trung Quốc','China',false'country',null),
('Nhật','Japan',false'country',null),
('Mông Cổ','Mongolia',false'country',null),
('Triều Tiên','North Korea',false'country',null),
('Hàn Quốc','South Korea',false'country',null),
('Đài Loan','Taiwan',false'country',null),
('Cam-pu-chia','Cambodia',false'country',null),
('Indonesia','Indonesia',false'country',null),
('Lào','Laos',false'country',null),
('Malaysia','Malaysia',false'country',null),
('Myanmar','Myanmar',false'country',null),
('Philippines','Philippines',false'country',null),
('Singapore','Singapore',false'country',null),
('Thái Lan','Thailand',false'country',null),
('Việt Nam','Vietnam',false'country',null),
('Australia','Australia',false'country',null),
('Fiji','Fiji',false'country',null),
('New Zealand','New Zealand',false'country',null),
('Ethiopia','Ethiopia',false'country',null),
('Kenya','Kenya',false'country',null),
('Somalia','Somalia',false'country',null),
('Sudan','Sudan',false'country',null),
('Tanzania','Tanzania',false'country',null),
('Uganda','Uganda',false'country',null),
('Angola','Angola',false'country',null),
('Botswana','Botswana',false'country',null),
('Cộng hòa Dân chủ Congo','Democratic Republic of the Congo',false'country',null),
('Madagascar','Madagascar',false'country',null),
('Mozambique','Mozambique',false'country',null),
('Namibia','Namibia',false'country',null),
('Nam Phi','South Africa',false'country',null),
('Zambia','Zambia',false'country',null),
('Zimbabwe','Zimbabwe',false'country',null),
( 'An Giang','An Giang',FALSE,'province',88),
( 'Bà Rịa-Vũng Tàu','Ba Ria Vung Tau',FALSE,'province',88),
( 'Bắc Giang','Bac Giang',FALSE,'province',88),
( 'Bắc Kạn','Bac Kan',FALSE,'province',88),
( 'Bạc Liêu','Bac Lieu',FALSE,'province',88),
( 'Bắc Ninh','Bac Ninh',FALSE,'province',88),
( 'Bến Tre','Ben Tre',FALSE,'province',88),
( 'Bình Dương','Binh Duong',FALSE,'province',88),
( 'Bình Định','Binh Dinh',FALSE,'province',88),
( 'Bình Phước','Binh Phuoc',FALSE,'province',88),
( 'Bình Thuận','Binh Thuan',FALSE,'province',88),
( 'Cà Mau','Ca Mau',FALSE,'province',88),
( 'Cần Thơ','Can Tho',FALSE,'province',88),
( 'Cao Bằng','Cao Bang',FALSE,'province',88),
( 'Đà Nẵng','Da Nang',FALSE,'province',88),
( 'Đắk Lắk','Dak Lak',FALSE,'province',88),
( 'Đắk Nông','Dak Nong',FALSE,'province',88),
( 'Điện Biên','Dien Bien',FALSE,'province',88),
( 'Đồng Nai','Dong Nai',FALSE,'province',88),
( 'Đồng Tháp','Dong Thap',FALSE,'province',88),
( 'Gia Lai','Gia Lai',FALSE,'province',88),
( 'Hà Giang','Ha Giang',FALSE,'province',88),
( 'Hà Nam','Ha Nam',FALSE,'province',88),
( 'Hà Nội','Ha Noi',FALSE,'province',88),
( 'Hà Tĩnh','Ha Tinh',FALSE,'province',88),
( 'Hải Dương','Hai Duong',FALSE,'province',88),
( 'Hải Phòng','Hai Phong',FALSE,'province',88),
( 'Hậu Giang','Hau Giang',FALSE,'province',88),
( 'Hồ Chí Minh','Ho Chi Minh',FALSE,'province',88),
( 'Hòa Bình','Hoa Binh',FALSE,'province',88),
( 'Hưng Yên','Hung Yen',FALSE,'province',88),
( 'Khánh Hòa','Khanh Hoa',FALSE,'province',88),
( 'Kiên Giang','Kien Giang',FALSE,'province',88),
( 'Kon Tum','Kon Tum',FALSE,'province',88),
( 'Lai Châu','Lai Chau',FALSE,'province',88),
( 'Lâm Đồng','Lam Dong',FALSE,'province',88),
( 'Lạng Sơn','Lang Son',FALSE,'province',88),
( 'Lào Cai','Lao Cai',FALSE,'province',88),
( 'Long An','Long An',FALSE,'province',88),
( 'Nam Định','Nam Dinh',FALSE,'province',88),
( 'Nghệ An','Nghe An',FALSE,'province',88),
( 'Ninh Bình','Ninh Binh',FALSE,'province',88),
( 'Ninh Thuận','Ninh Thuan',FALSE,'province',88),
( 'Phú Thọ','Phu Tho',FALSE,'province',88),
( 'Phú Yên','Phu Yen',FALSE,'province',88),
( 'Quảng Bình','Quang Binh',FALSE,'province',88),
( 'Quảng Nam','Quang Nam',FALSE,'province',88),
( 'Quảng Ngãi','Quang Ngai',FALSE,'province',88),
( 'Quảng Ninh','Quang Ninh',FALSE,'province',88),
( 'Quảng Trị','Quang Tri',FALSE,'province',88),
( 'Sóc Trăng','Soc Trang',FALSE,'province',88),
( 'Sơn La','Son La',FALSE,'province',88),
( 'Tây Ninh','Tay Ninh',FALSE,'province',88),
( 'Thái Bình','Thai Binh',FALSE,'province',88),
( 'Thái Nguyên','Thai Nguyen',FALSE,'province',88),
( 'Thanh Hóa','Thanh Hoa',FALSE,'province',88),
( 'Thừa Thiên-Huế','Thua Thien Hue',FALSE,'province',88),
( 'Tiền Giang','Tien Giang',FALSE,'province',88),
( 'Trà Vinh','Tra Vinh',FALSE,'province',88),
( 'Tuyên Quang','Tuyen Quang',FALSE,'province',88),
( 'Vĩnh Long','Vinh Long',FALSE,'province',88),
( 'Vĩnh Phúc','Vinh Phuc',FALSE,'province',88),
( 'Yên Bái','Yen Bai',FALSE,'province',88),
